"""Match rate of 'extra' name words, learned from the stage-1 training pairs.

Look-alike businesses are generated by appending words from their own vocabulary
("enterprises", "trading", "group", "holdings", "exports", ...: ~0-3% true matches when it is
the query's only extra word), while record noise adds different ones ("center", "services",
transliterated variants: ~85-95%). For every word that one side of a plausible pair has and the
other lacks, this stores a smoothed true-match rate, per side (query extra / entity extra).

The table comes from the stage-1 training queries only, which are disjoint from the held-out
entities stage 2 is trained and validated on, so the stage-2 features built from it do not see
their own labels. Output: work/xword_rates.parquet (w, side, n, rate).
"""
import glob
import time

import polars as pl

import config
import fine
from pipeline import load_records, gt_pairs

MIN_COS = 0.6   # close pairs only: the rates are meant for the pairs stage 2 has to decide
MIN_N = 20      # words seen fewer times are left out (the feature treats them as unknown)
SMOOTH = 20     # pseudo-counts toward the overall rate


def main():
    t = time.time()
    rec = load_records("train").select("rid", "entity_id", "core")
    gt = gt_pairs(rec)
    tk = rec.select("rid", pl.col("core").fill_null("").str.split(" ")
                    .list.eval(pl.element().filter(pl.element() != "")).alias("tk"))
    pairs = (pl.scan_parquet(glob.glob(config.work("feat_tr_*.parquet"))).select("q_rid", "e_rid", "cos_name")
             .filter(pl.col("cos_name") >= MIN_COS).select("q_rid", "e_rid").collect())
    P = (pairs.join(tk.rename({"rid": "q_rid", "tk": "tq"}), on="q_rid")
         .join(tk.rename({"rid": "e_rid", "tk": "te"}), on="e_rid")
         .join(gt.rename({"true_e": "e_rid"}).with_columns(pl.lit(1, pl.Int8).alias("y")),
               on=["q_rid", "e_rid"], how="left").with_columns(pl.col("y").fill_null(0))
         .with_columns(pl.col("tq").list.set_difference("te").alias("xq"),
                       pl.col("te").list.set_difference("tq").alias("xe")))
    out = []
    # a word's own effect: count it only when it is the whole difference on the other side too,
    # i.e. the query's extra words when the query contains every entity word (and vice versa)
    for side, col, other in (("q", "xq", "xe"), ("e", "xe", "xq")):
        x = (P.filter(pl.col(other).list.len() == 0).select("y", pl.col(col).alias("w"))
             .explode("w", empty_as_null=True).drop_nulls("w"))
        prior = float(x["y"].mean())
        out.append(x.group_by("w").agg(pl.len().alias("n"), pl.col("y").sum().alias("ys"))
                   .filter(pl.col("n") >= MIN_N)
                   .with_columns(((pl.col("ys") + SMOOTH * prior) / (pl.col("n") + SMOOTH))
                                 .cast(pl.Float32).alias("rate"), pl.lit(side).alias("side"))
                   .select("w", "side", "n", "rate"))
        print(f"[xwords] {side}: {out[-1].height:,} words, prior {prior:.3f}", flush=True)
    tab = pl.concat(out)
    tab.write_parquet(config.work("xword_rates.parquet"))
    sigs(pairs, rec, gt)
    print(f"[xwords] {pairs.height:,} pairs  done {time.time() - t:.0f}s")


def sigs(pairs, rec, gt):
    """Match rate of every diff signature (fine.signature) on the same close pairs."""
    t = time.time()
    r = load_records("train").select("rid", "core", "nums", "legal", "country")
    P = (pairs.join(r.rename(lambda c: c + "_q"), left_on="q_rid", right_on="rid_q")
         .join(r.rename(lambda c: c + "_e"), left_on="e_rid", right_on="rid_e")
         .join(gt.rename({"true_e": "e_rid"}).with_columns(pl.lit(1, pl.Int8).alias("y")),
               on=["q_rid", "e_rid"], how="left").with_columns(pl.col("y").fill_null(0)))
    fs, cs = [], []
    for row in zip(P["core_q"].to_list(), P["core_e"].to_list(), P["nums_q"].to_list(),
                   P["nums_e"].to_list(), P["legal_q"].to_list(), P["legal_e"].to_list(),
                   P["country_q"].to_list()):
        f, c = fine.signature(*row)
        fs.append(f)
        cs.append(c)
    P = P.select("y").with_columns(pl.Series("fine", fs), pl.Series("coarse", cs))
    prior = float(P["y"].mean())
    out = []
    for kind in ("fine", "coarse"):
        out.append(P.group_by(kind).agg(pl.len().alias("n"), pl.col("y").sum().alias("ys"))
                   .filter(pl.col("n") >= MIN_N)
                   .with_columns(((pl.col("ys") + SMOOTH * prior) / (pl.col("n") + SMOOTH))
                                 .cast(pl.Float32).alias("rate"), pl.lit(kind).alias("kind"))
                   .select(pl.col(kind).alias("sig"), "kind", "n", "rate"))
        print(f"[sigs] {kind}: {out[-1].height:,} signatures", flush=True)
    pl.concat(out).write_parquet(config.work("sig_rates.parquet"))
    print(f"[sigs] prior {prior:.3f}  {time.time() - t:.0f}s", flush=True)


if __name__ == "__main__":
    main()
